CXX = g++

all:
	$(CXX) main.cpp -o main -std=c++23

# all:
# 	$(CC) -shared -fPIC --no-gnu-unique main.cpp -o hyprplugin.so -g `pkg-config --cflags pixman-1 libdrm hyprland pangocairo libinput libudev wayland-server xkbcommon` -std=c++2b -O2
